export const TRANSLATES = {
    bannerMotto: {
        rom: "Drumurile viitorului, construite azi",
        rus: "Дороги будущего, построенные сегодня",
        eng: "Roads of the future, built today",
        arb: "طرق المستقبل، بنيت اليوم",
    },
    ourServices: {
        rom: "Serviciile noastre",
        rus: "Наши услуги",
        eng: "Our services",
        arb: "خدماتنا",
    },
    asphaltFactory: {
        rom: "Dispune de uzina de asfalt „BENINGHOVEN” cu o capacitate de 200 tone/H",
        rus: "Имеет асфальтный завод «BENINGHOVEN» мощностью 200 тонн/ч",
        eng: "Has an asphalt plant „BENINGHOVEN” with a capacity of 200 tons/h",
        arb: "لديه مصنع للأسفلت «BENINGHOVEN» بطاقة 200 طن / ساعة",
    },
    asphaltReparation: {
        rom: "Asfaltarea și reparația drumurilor",
        rus: "Асфальтирование и ремонт дорог",
        eng: "Asphalting and road repair",
        arb: "تعبيد الطرق وإصلاحها",
    },
    depositCapacity: {
        rom: "Deține un depozit cu un volum de 500.000 m3 pentru depozitarea materialelor de construcții.",
        rus: "Имеет склад с объемом 500.000 м3 для хранения строительных материалов.",
        eng: "Has a warehouse with a volume of 500,000 m3 for storing construction materials.",
        arb: "لديه مستودع بحجم 500.000 م3 لتخزين مواد البناء.",
    },
    descoverMore: {
        rom: "Descoperă mai multe",
        rus: "Узнать больше",
        eng: "Discover more",
        arb: "اكتشف أكثر",
    },
    needExpertsBanner: {
        rom: "Ai nevoie de experți în infrastructură rutieră? ",
        rus: "Нужны эксперты в дорожной инфраструктуре?",
        eng: "Do you need road infrastructure experts?",
        arb: "هل تحتاج إلى خبراء في البنية التحتية للطرق؟",
    },
    needExpertsBanner2: {
        rom: "Suntem la un click distanță!",
        rus: "Мы находимся в одном клике!",
        eng: "We are one click away!",
        arb: "نحن على بعد نقرة واحدة!",
    },
    contactUs: {
        rom: "Contactează-ne",
        rus: "Связаться с нами",
        eng: "Contact us",
        arb: "اتصل بنا",
    },
    lastNews: {
        rom: "Ultimele noutăți",
        rus: "Последние новости",
        eng: "Latest news",
        arb: "أحدث الأخبار",
    },
    seeAll: {
        rom: "Vezi tot",
        rus: "Смотреть все",
        eng: "See all",
        arb: "اظهار الكل",
    },
    finishedProjects: {
        rom: "Proiecte finalizate",
        rus: "Завершенные проекты",
        eng: "Finished projects",
        arb: "المشاريع المنتهية",
    },
    yearsOfExperience: {
        rom: "Ani de experiență",
        rus: "Лет опыта",
        eng: "Years of experience",
        arb: "سنوات من الخبرة",
    },
    machinery: {
        rom: "Utilaje",
        rus: "Оборудование",
        eng: "Machinery",
        arb: "آلات",
    },
    experts: {
        rom: "Specialiști",
        rus: "Эксперты",
        eng: "Experts",
        arb: "خبراء",
    },
    letsWorkTogether: {
        rom: "Ce zici să lucrăm împreună?",
        rus: "Давайте работать вместе",
        eng: "Let's work together",
        arb: "لنعمل معًا؟",
    },
    partners: {
        rom: "Parteneri",
        rus: "Партнеры",
        eng: "Partners",
        arb: "شركاء",
    },
    address: {
        rom: "Adresa",
        rus: "Адрес",
        eng: "Address",
        arb: "عنوان",
    },
    contabilityPhone: {
        rom: "Telefon contabilitate",
        rus: "Телефон бухгалтерии",
        eng: "Accounting phone",
        arb: "هاتف المحاسبة",
    },
    clientsRelation: {
        rom: "Relații cu clienții",
        rus: "Отношения с клиентами",
        eng: "Customer relations",
        arb: "علاقات العملاء",
    },
    email: {
        rom: "Email",
        rus: "Электронная почта",
        eng: "Email",
        arb: "البريد الإلكتروني",
    },
    phone: {
        rom: "Telefon",
        rus: "Телефон",
        eng: "Phone",
        arb: "هاتف",
    },
    rights: {
        rom: "Toate drepturile rezervate",
        rus: "Все права защищены",
        eng: "All rights reserved",
        arb: "كل الحقوق محفوظة",
    },
    home: {
        rom: "Acasă",
        rus: "Главная",
        eng: "Home",
        arb: "الصفحة الرئيسية",
    },
    contacts: {
        rom: "Contacte",
        rus: "Контакты",
        eng: "Contacts",
        arb: "جهات الاتصال",
    },
    aboutUs: {
        rom: "Despre noi",
        rus: "О нас",
        eng: "About us",
        arb: "معلومات عنا",
    },
    events: {
        rom: "Evenimente",
        rus: "События",
        eng: "Events",
        arb: "أحداث",
    },
    discussIdea: {
        rom: "pentru a discuta despre ideia ta",
        rus: "чтобы обсудить вашу идею",
        eng: "to discuss your idea",
        arb: "لمناقشة فكرتك",
    },
    nameSurname: {
        rom: "Nume și prenume",
        rus: "Имя и фамилия",
        eng: "Name and surname",
        arb: "الاسم واللقب",
    },
    message: {
        rom: "Mesaj",
        rus: "Сообщение",
        eng: "Message",
        arb: "رسالة",
    },
    send: {
        rom: "Trimite",
        rus: "Отправить",
        eng: "Send",
        arb: "إرسال",
    },
    leaveMessage: {
        rom: "Lăsați-ne un mesaj",
        rus: "Оставьте нам сообщение",
        eng: "Leave us a message",
        arb: "اترك لنا رسالة",
    },
};
